name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - name: Use Julia cache
        uses: julia-actions/cache@v2

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path = pwd()))
            Pkg.instantiate()'
            
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}